# Mi repaso

##  1. Se obtienen los datos de accidents de tráfico del Ayuntamiento de Madrid

In [1]:
! wget -N https://datos.madrid.es/egob/catalogo/207831-2-accidentes-trafico.xls

--2019-01-20 11:44:07--  https://datos.madrid.es/egob/catalogo/207831-2-accidentes-trafico.xls
Resolving datos.madrid.es (datos.madrid.es)... 149.235.17.74
Connecting to datos.madrid.es (datos.madrid.es)|149.235.17.74|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://datos.madrid.es:443/egobfiles/MANUAL/207831/03_%20ACCIDENTES%20POR%20TIPO%20Y%20DIA%20SEMANA.xls [following]
--2019-01-20 11:44:07--  https://datos.madrid.es/egobfiles/MANUAL/207831/03_%20ACCIDENTES%20POR%20TIPO%20Y%20DIA%20SEMANA.xls
Connecting to datos.madrid.es (datos.madrid.es)|149.235.17.74|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘207831-2-accidentes-trafico.xls’ not modified on server. Omitting download.

_Nota_: -N no se baja el archivo a menos que haya cambiado. https://serverfault.com/a/379060

## 2.Leemos la hoja correspondiente a 2009

Hay que saltarse las primeras filas

In [2]:
import pandas as pd

accidents = pd.read_excel('207831-2-accidentes-trafico.xls',
                           sheet_name='2009',header=6,usecols="A:K",skip_footer=1)

accidents

,Tipo Accidente,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
0,Dia Semana,Nº Accidentes,Nº Accidentes,Nº Accidentes,Nº Accidentes,Nº Accidentes,Nº Accidentes,Nº Accidentes,Nº Accidentes,Nº Accidentes,Nº Accidentes
1,LUNES,975,138,310,280,16,124,36,6,7,19
2,MARTES,931,120,283,242,9,124,28,12,17,23
3,MIERCOLES,1054,141,280,261,11,139,35,8,17,21
4,JUEVES,1026,113,317,255,15,138,43,12,22,21
5,VIERNES,1117,161,338,250,14,133,28,10,16,22
6,SABADO,762,62,433,167,15,57,36,10,7,14
7,DOMINGO,633,55,429,127,18,53,25,18,7,14

##  3. Adaptamos el dataframe a nuestras necesidades

### 3.1 Borramos la fila que repite 'Nº accidents', que es innecesaria

In [3]:
accidents.index

RangeIndex(start=0, stop=8, step=1)

In [4]:
accidents.drop(labels=accidents.index[0], inplace=True)
accidents

,Tipo Accidente,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
1,LUNES,975,138,310,280,16,124,36,6,7,19
2,MARTES,931,120,283,242,9,124,28,12,17,23
3,MIERCOLES,1054,141,280,261,11,139,35,8,17,21
4,JUEVES,1026,113,317,255,15,138,43,12,22,21
5,VIERNES,1117,161,338,250,14,133,28,10,16,22
6,SABADO,762,62,433,167,15,57,36,10,7,14
7,DOMINGO,633,55,429,127,18,53,25,18,7,14

###  3.2 Las columnas tienen espacios en los nombres. Los limpiamos.

In [5]:
accidents.columns

Index(['Tipo Accidente', 'COLISIÓN DOBLE                          ',
       'COLISIÓN MÚLTIPLE                       ',
       'CHOQUE CON OBJETO FIJO                  ',
       'ATROPELLO                               ',
       'VUELCO                                  ',
       'CAÍDA MOTOCICLETA                       ',
       'CAÍDA CICLOMOTOR                        ',
       'CAÍDA BICICLETA                         ',
       'CAÍDA VIAJERO BUS                       ',
       'OTRAS CAUSAS                            '],
      dtype='object')

In [6]:
accidents.columns = accidents.columns.str.strip()

In [7]:
accidents.columns

Index(['Tipo Accidente', 'COLISIÓN DOBLE', 'COLISIÓN MÚLTIPLE',
       'CHOQUE CON OBJETO FIJO', 'ATROPELLO', 'VUELCO', 'CAÍDA MOTOCICLETA',
       'CAÍDA CICLOMOTOR', 'CAÍDA BICICLETA', 'CAÍDA VIAJERO BUS',
       'OTRAS CAUSAS'],
      dtype='object')

### 3.3 Modificamos el nombre de la primera columna

In [8]:
accidents.columns[0]

'Tipo Accidente'

In [9]:
accidents.rename(columns={ accidents.columns[0]:"DÍA SEMANA"}, inplace=True)
accidents

,DÍA SEMANA,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
1,LUNES,975,138,310,280,16,124,36,6,7,19
2,MARTES,931,120,283,242,9,124,28,12,17,23
3,MIERCOLES,1054,141,280,261,11,139,35,8,17,21
4,JUEVES,1026,113,317,255,15,138,43,12,22,21
5,VIERNES,1117,161,338,250,14,133,28,10,16,22
6,SABADO,762,62,433,167,15,57,36,10,7,14
7,DOMINGO,633,55,429,127,18,53,25,18,7,14

### 3.4 Añadimos una columna _AÑO_

Esto lo hacemos porque posteriormente cargaremos el resto de hojas y juntaremos todos los datos.

In [10]:
accidents["AÑO"] = 2009
accidents

,DÍA SEMANA,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,AÑO
1,LUNES,975,138,310,280,16,124,36,6,7,19,2009
2,MARTES,931,120,283,242,9,124,28,12,17,23,2009
3,MIERCOLES,1054,141,280,261,11,139,35,8,17,21,2009
4,JUEVES,1026,113,317,255,15,138,43,12,22,21,2009
5,VIERNES,1117,161,338,250,14,133,28,10,16,22,2009
6,SABADO,762,62,433,167,15,57,36,10,7,14,2009
7,DOMINGO,633,55,429,127,18,53,25,18,7,14,2009

### 3.5 Añadimos una columna _FIN DE SEMANA_

In [11]:
def is_weekend(day):
    if day.upper() == "SABADO": return True
    if day.upper() == "DOMINGO": return True
    
    return False

In [12]:
accidents["FIN DE SEMANA"] = accidents["DÍA SEMANA"].apply(is_weekend)
accidents

,DÍA SEMANA,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,AÑO,FIN DE SEMANA
1,LUNES,975,138,310,280,16,124,36,6,7,19,2009,False
2,MARTES,931,120,283,242,9,124,28,12,17,23,2009,False
3,MIERCOLES,1054,141,280,261,11,139,35,8,17,21,2009,False
4,JUEVES,1026,113,317,255,15,138,43,12,22,21,2009,False
5,VIERNES,1117,161,338,250,14,133,28,10,16,22,2009,False
6,SABADO,762,62,433,167,15,57,36,10,7,14,2009,True
7,DOMINGO,633,55,429,127,18,53,25,18,7,14,2009,True

###  3.6 Añadimos una columna _VEHÍCULO DOS RUEDAS_

In [13]:
accidents["VEHÍCULO DOS RUEDAS"] = accidents["CAÍDA MOTOCICLETA"]+ accidents["CAÍDA CICLOMOTOR"]+ accidents["CAÍDA BICICLETA"]
accidents

,DÍA SEMANA,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,AÑO,FIN DE SEMANA,VEHÍCULO DOS RUEDAS
1,LUNES,975,138,310,280,16,124,36,6,7,19,2009,False,166
2,MARTES,931,120,283,242,9,124,28,12,17,23,2009,False,164
3,MIERCOLES,1054,141,280,261,11,139,35,8,17,21,2009,False,182
4,JUEVES,1026,113,317,255,15,138,43,12,22,21,2009,False,193
5,VIERNES,1117,161,338,250,14,133,28,10,16,22,2009,False,171
6,SABADO,762,62,433,167,15,57,36,10,7,14,2009,True,103
7,DOMINGO,633,55,429,127,18,53,25,18,7,14,2009,True,96

###  3.7 Reordenamos columnas

In [14]:
def select_columns_by_index(dataframe,*indexes):
    all_column_names = dataframe.columns
    selected_column_names = map(lambda index : all_column_names[index], indexes)
    return dataframe[list(selected_column_names)]

select_columns_by_index(accidents,0,12,1,2,3,4,5,6,7,8,9,10,13,11)

,DÍA SEMANA,FIN DE SEMANA,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,VEHÍCULO DOS RUEDAS,AÑO
1,LUNES,False,975,138,310,280,16,124,36,6,7,19,166,2009
2,MARTES,False,931,120,283,242,9,124,28,12,17,23,164,2009
3,MIERCOLES,False,1054,141,280,261,11,139,35,8,17,21,182,2009
4,JUEVES,False,1026,113,317,255,15,138,43,12,22,21,193,2009
5,VIERNES,False,1117,161,338,250,14,133,28,10,16,22,171,2009
6,SABADO,True,762,62,433,167,15,57,36,10,7,14,103,2009
7,DOMINGO,True,633,55,429,127,18,53,25,18,7,14,96,2009

## 4. Leyendo resto de hojas

El objetivo sería aglutinar todos los datos de todos los años en un sólo dataframe. EL problema es que, para el año 2013, los datos empiezan en la fila 3. Vamos a representar esto:

In [15]:
class ExcelSheet:
  def __init__(self, year, first_row):
    self.year = year
    self.first_row = first_row

In [16]:
excel_sheets = [
    ExcelSheet('2009', 6),
    ExcelSheet('2010', 6),
    ExcelSheet('2011', 6),
    ExcelSheet('2012', 6),
    ExcelSheet('2013', 3),
    ExcelSheet('2014', 6),
    ExcelSheet('2015', 6),
    ExcelSheet('2016', 6),
]

### 4.1 Creamos una función que haga todos los pasos de los puntos 1-3

In [21]:
def read_excel_sheet(sheet):
    dataframe = pd.read_excel('207831-2-accidentes-trafico.xls',
                              sheet_name=sheet.year,header=sheet.first_row,usecols="A:K",skip_footer=1)
    dataframe.drop(labels=dataframe.index[0], inplace=True)
    dataframe.columns = dataframe.columns.str.strip()
    dataframe.rename(columns={ dataframe.columns[0]:"DÍA SEMANA"}, inplace=True)
    dataframe["AÑO"] = int(sheet.year)
    dataframe["FIN DE SEMANA"] = dataframe["DÍA SEMANA"].apply(is_weekend)
    dataframe["VEHÍCULO DOS RUEDAS"] = dataframe["CAÍDA MOTOCICLETA"]+ dataframe["CAÍDA CICLOMOTOR"]+ dataframe["CAÍDA BICICLETA"]
    select_columns_by_index(dataframe,0,12,1,2,3,4,5,6,7,8,9,10,13,11)
    
    return dataframe

### 4.2 Obtenemos los dataframes de cada año usando la función

In [22]:
all_years_accident_list = list(map(lambda sheet:read_excel_sheet(sheet), excel_sheets))
all_years_accident_list

[  DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            975               138                    310
 2     MARTES            931               120                    283
 3  MIERCOLES           1054               141                    280
 4     JUEVES           1026               113                    317
 5    VIERNES           1117               161                    338
 6     SABADO            762                62                    433
 7    DOMINGO            633                55                    429

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       280     16               124               36               6
 2       242      9               124               28              12
 3       261     11               139               35               8
 4       255     15               138               43              12
 5       250     14               133               28              10
 6       167     15                57               36              10
 7       127     18                53               25              18

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                 7           19  2009          False                 166
 2                17           23  2009          False                 164
 3                17           21  2009          False                 182
 4                22           21  2009          False                 193
 5                16           22  2009          False                 171
 6                 7           14  2009           True                 103
 7                 7           14  2009           True                  96  ,
   DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            858               112                    256
 2     MARTES            925               102                    224
 3  MIERCOLES           1020               118                    241
 4     JUEVES            941               124                    239
 5    VIERNES           1045               159                    306
 6     SABADO            701                72                    405
 7    DOMINGO            628                58                    365

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       246     10                98               24              12
 2       252     15               120               30               9
 3       250     18               123               36               9
 4       241      7               141               20              16
 5       273     10               117               37              10
 6       175     26                52               17              11
 7       133     24                40               24              14

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                17           13  2010          False                 134
 2                14           12  2010          False                 159
 3                24            8  2010          False                 168
 4                18           21  2010          False                 177
 5                16           13  2010          False                 164
 6                 9            8  2010           True                  80
 7                 7            9  2010           True                  78  ,
   DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            867               115                    250
 2     MARTES            971               125                    239
 3  MIERCOLES            961               102                    227
 4     JUEVES            947               126                    278
 5    VIERNES           1094               169                    304
 6     SABADO            758                82                    412
 7    DOMINGO            640                57                    398

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       245      9               125               32              18
 2       265      6               123               16              14
 3       267      6               139               32              12
 4       245      7               149               23              15
 5       275     13               154               36              11
 6       153     19                66               24              19
 7       116     16                47               22              25

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                 9            3  2011          False                 175
 2                14            9  2011          False                 153
 3                17            8  2011          False                 183
 4                 9           11  2011          False                 187
 5                15            8  2011          False                 201
 6                10           13  2011           True                 109
 7                 1           10  2011           True                  94  ,
   DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            921               121                    233
 2     MARTES            929               123                    183
 3  MIERCOLES            936               132                    234
 4     JUEVES           1001               135                    247
 5    VIERNES           1073               148                    304
 6     SABADO            725                69                    409
 7    DOMINGO            585                56                    364

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       208      9               127               25              16
 2       251      8               134               26              25
 3       246     13               111               25              26
 4       262     12               152               25              10
 5       239     14               132               33              14
 6       155     17                66               24              17
 7       135     19                52               29              18

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                 8           12  2012          False                 168
 2                11            8  2012          False                 185
 3                18           11  2012          False                 162
 4                10           10  2012          False                 187
 5                11           12  2012          False                 179
 6                 7           11  2012           True                 107
 7                 4           10  2012           True                  99  ,
   DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            887               109                    220
 2     MARTES            977               129                    245
 3  MIERCOLES            916               100                    245
 4     JUEVES            956               120                    230
 5    VIERNES           1080               145                    290
 6     SABADO            756                60                    389
 7    DOMINGO            585                60                    356

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       224     10               162               19              16
 2       242      5               142               17              18
 3       257      6               175               23              18
 4       242     11               153               19              13
 5       241     11               148               23              26
 6       158     15                76               15              25
 7       122      9                71               21              24

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                 9           10  2013          False                 197
 2                16            7  2013          False                 177
 3                 7            7  2013          False                 216
 4                11            8  2013          False                 185
 5                19           14  2013          False                 197
 6                11            6  2013           True                 116
 7                 3            9  2013           True                 116  ,
   DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            881               112                    256
 2     MARTES            952               128                    223
 3  MIERCOLES           1001               130                    197
 4     JUEVES            958               137                    280
 5    VIERNES            978               147                    291
 6     SABADO            696                55                    372
 7    DOMINGO            590                60                    378

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       268     11               140               24              33
 2       244     10               158               20              21
 3       226     12               166               25              28
 4       214     19               179               20              37
 5       237     10               179               26              28
 6       168     17                97               16              47
 7       126     15                68               19              38

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                21           11  2014          False                 197
 2                15           11  2014          False                 199
 3                20           16  2014          False                 219
 4                13           12  2014          False                 236
 5                12            8  2014          False                 233
 6                 2            6  2014           True                 160
 7                 6           14  2014           True                 125  ,
   DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            902               111                    245
 2     MARTES            936               128                    225
 3  MIERCOLES           1030               120                    209
 4     JUEVES            961               116                    203
 5    VIERNES            983               148                    259
 6     SABADO            712                53                    347
 7    DOMINGO            597                60                    316

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       220      9               169               23              31
 2       226     14               170               27              31
 3       250      3               171               26              28
 4       254      9               140               24              30
 5       262      5               157               28              46
 6       164     12                94               18              24
 7       149      8                82               20              49

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                 9           10  2015          False                 223
 2                10           10  2015          False                 228
 3                12           14  2015          False                 225
 4                19            7  2015          False                 194
 5                17           12  2015          False                 231
 6                12            4  2015           True                 136
 7                 6            6  2015           True                 151  ,
   DÍA SEMANA COLISIÓN DOBLE COLISIÓN MÚLTIPLE CHOQUE CON OBJETO FIJO  \
 1      LUNES            884               133                    275
 2     MARTES            919               107                    209
 3  MIERCOLES            959               120                    219
 4     JUEVES           1004               119                    254
 5    VIERNES           1111               165                    304
 6     SABADO            734                85                    365
 7    DOMINGO            647                67                    339

   ATROPELLO VUELCO CAÍDA MOTOCICLETA CAÍDA CICLOMOTOR CAÍDA BICICLETA  \
 1       222      5               156               21              28
 2       236     10               186               28              42
 3       258      5               179               23              39
 4       249     15               199               34              37
 5       307     13               184               45              40
 6       170     14                98               24              48
 7       118     13                87               37              39

   CAÍDA VIAJERO BUS OTRAS CAUSAS   AÑO  FIN DE SEMANA VEHÍCULO DOS RUEDAS
 1                17           13  2016          False                 205
 2                12           10  2016          False                 256
 3                15            6  2016          False                 241
 4                19            8  2016          False                 270
 5                11           11  2016          False                 269
 6                 9            9  2016           True                 170
 7                10            8  2016           True                 163  ]

###  Las unimos en un solo dataframe

Ponemos ignore_index=True para que cree un nuevo índice autonumerado en lugar de tener 1,2,3,4,5,6,7,1,2,3,4,5,6...

In [26]:
all_accidents = pd.concat(all_years_accident_list, ignore_index=True)
all_accidents

,DÍA SEMANA,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,AÑO,FIN DE SEMANA,VEHÍCULO DOS RUEDAS
0,LUNES,975,138,310,280,16,124,36,6,7,19,2009,False,166
1,MARTES,931,120,283,242,9,124,28,12,17,23,2009,False,164
2,MIERCOLES,1054,141,280,261,11,139,35,8,17,21,2009,False,182
3,JUEVES,1026,113,317,255,15,138,43,12,22,21,2009,False,193
4,VIERNES,1117,161,338,250,14,133,28,10,16,22,2009,False,171
5,SABADO,762,62,433,167,15,57,36,10,7,14,2009,True,103
6,DOMINGO,633,55,429,127,18,53,25,18,7,14,2009,True,96
7,LUNES,858,112,256,246,10,98,24,12,17,13,2010,False,134
8,MARTES,925,102,224,252,15,120,30,9,14,12,2010,False,159
9,MIERCOLES,1020,118,241,250,18,123,36,9,24,8,2010,False,168
10,JUEVES,941,124,239,241,7,141,20,16,18,21,2010,False,177
11,VIERNES,1045,159,306,273,10,117,37,10,16,13,2010,False,164
12,SABADO,701,72,405,175,26,52,17,11,9,8,2010,True,80
13,DOMINGO,628,58,365,133,24,40,24,14,7,9,2010,True,78
14,LUNES,867,115,250,245,9,125,32,18,9,3,2011,False,175
15,MARTES,971,125,239,265,6,123,16,14,14,9,2011,False,153
16,MIERCOLES,961,102,227,267,6,139,32,12,17,8,2011,False,183
17,JUEVES,947,126,278,245,7,149,23,15,9,11,2011,False,187
18,VIERNES,1094,169,304,275,13,154,36,11,15,8,2011,False,201
19,SABADO,758,82,412,153,19,66,24,19,10,13,2011,True,109
20,DOMINGO,640,57,398,116,16,47,22,25,1,10,2011,True,94
21,LUNES,921,121,233,208,9,127,25,16,8,12,2012,False,168
22,MARTES,929,123,183,251,8,134,26,25,11,8,2012,False,185
23,MIERCOLES,936,132,234,246,13,111,25,26,18,11,2012,False,162
24,JUEVES,1001,135,247,262,12,152,25,10,10,10,2012,False,187
25,VIERNES,1073,148,304,239,14,132,33,14,11,12,2012,False,179
26,SABADO,725,69,409,155,17,66,24,17,7,11,2012,True,107
27,DOMINGO,585,56,364,135,19,52,29,18,4,10,2012,True,99
28,LUNES,887,109,220,224,10,162,19,16,9,10,2013,False,197
29,MARTES,977,129,245,242,5,142,17,18,16,7,2013,False,177
30,MIERCOLES,916,100,245,257,6,175,23,18,7,7,2013,False,216
31,JUEVES,956,120,230,242,11,153,19,13,11,8,2013,False,185
32,VIERNES,1080,145,290,241,11,148,23,26,19,14,2013,False,197
33,SABADO,756,60,389,158,15,76,15,25,11,6,2013,True,116
34,DOMINGO,585,60,356,122,9,71,21,24,3,9,2013,True,116
35,LUNES,881,112,256,268,11,140,24,33,21,11,2014,False,197
36,MARTES,952,128,223,244,10,158,20,21,15,11,2014,False,199
37,MIERCOLES,1001,130,197,226,12,166,25,28,20,16,2014,False,219
38,JUEVES,958,137,280,214,19,179,20,37,13,12,2014,False,236
39,VIERNES,978,147,291,237,10,179,26,28,12,8,2014,False,233
40,SABADO,696,55,372,168,17,97,16,47,2,6,2014,True,160
41,DOMINGO,590,60,378,126,15,68,19,38,6,14,2014,True,125
42,LUNES,902,111,245,220,9,169,23,31,9,10,2015,False,223
43,MARTES,936,128,225,226,14,170,27,31,10,10,2015,False,228
44,MIERCOLES,1030,120,209,250,3,171,26,28,12,14,2015,False,225
45,JUEVES,961,116,203,254,9,140,24,30,19,7,2015,False,194
46,VIERNES,983,148,259,262,5,157,28,46,17,12,2015,False,231
47,SABADO,712,53,347,164,12,94,18,24,12,4,2015,True,136
48,DOMINGO,597,60,316,149,8,82,20,49,6,6,2015,True,151
49,LUNES,884,133,275,222,5,156,21,28,17,13,2016,False,205
50,MARTES,919,107,209,236,10,186,28,42,12,10,2016,False,256
51,MIERCOLES,959,120,219,258,5,179,23,39,15,6,2016,False,241
52,JUEVES,1004,119,254,249,15,199,34,37,19,8,2016,False,270
53,VIERNES,1111,165,304,307,13,184,45,40,11,11,2016,False,269
54,SABADO,734,85,365,170,14,98,24,48,9,9,2016,True,170
55,DOMINGO,647,67,339,118,13,87,37,39,10,8,2016,True,163